import supybot.utils as utils

beverages = utils.gen.InsensitivePreservingDict({
  "cocktails" : {
    "Apple Tini" : "0",
    "B52" : "1",
    "Black Russian" : "2",
    "Bloody Mary" : "3",
    "Cosmopolitan" : "4",
    "Daiquiri" : "5",
    "Disaronno and Coke" : "6",
    "Double on the Rocks" : "7",
    "Dry Manhattan" : "8",
    "Kamikaze" : "9",
    "Long Island Iced Tea" : "10",
    "Lemon Drop" : "11",
    "Manhattan" : "12",
    "Margarita" : "13",
    "Martini" : "14",
    "Dirty Martini" : "15",
    "Wet Martini" : "16",
    "Dry Martini" : "17",
    "Mojito" : "18",
    "Mai Thai" : "19",
    "Mimosa" : "20",
    "Mint Julep" : "21",
    "Pina Colada" : "22",
    "Rum and Coke" : "23",
    "Seabreeze" : "24",
    "Screwdriver" : "25",
    "Sex on the Beach" : "26",
    "Slippery  Nipple" : "27",
    "Tom Collins" : "28",
    "Tequila Sunrise" : "29",
    "Vodka Martini" : "30",
    "Zombie" : "31",
    "White Russian" : "32",
    "Singapore Sling" : "33",
    "Whiskey Sour" : "34"
  },
  'shots' : {
    "Absinthe" : "35",
    "Bourbon" : "36",
    "Everclear" : "37",
    "Flavored Vodka" : "38",
    "Gin" : "39",
    "Malibu Rum" : "40",
    "Rum" : "41",
    "Scotch" : "42",
    "Tequila" : "43",
    "Vodka" : "44",
    "Whiskey" : "45"
  },
  'wine' : {
    "Red Wine" : "46",
    "White Wine" : "47",
    "Rose Wine" : "48",
    "Sparkling Wine" : "49"
  },
  'beer' : {
    "Amstel Light Amstel Light" : "50",
    "Alaskan Amber" : "51",
    "Alaskan Pale Ale" : "52",
    "Alaskan Stout" : "53",
    "Alaskan ESB" : "54",
    "Alaskan Smoked Porter" : "55",
    "Alaskan Winter Ale" : "56",
    "Anchor Steam" : "57",
    "Anchor Liberty Ale" : "58",
    "Anchor Porter" : "59",
    "Anchor Old Foghorn" : "60",
    "Anchor Small" : "61",
    "Anderson Valley Boont Amber" : "62",
    "Anderson Valley Hop Ottin'" : "63",
    "Anderson Valley Poleeko Gold" : "64",
    "Anderson Valley Belk's ESB" : "65",
    "Anderson Valley Barney Flats Oatmeal" : "66",
    "Anderson Valley Winter Solstice" : "67",
    "Anderson Valley High Rollers Wheat" : "68",
    "Anderson Valley Deep Enders Porter" : "69",
    "Beamish Stout" : "70",
    "Beck's" : "71",
    "Bell's/Kalamazoo Two Hearted Ale" : "72",
    "Bell's/Kalamazoo Amber Ale" : "73",
    "Bell's/Kalamazoo Pale Ale" : "74",
    "Bell's/Kalamazoo Kalamazoo Stout" : "75",
    "Bell's/Kalamazoo Oberon" : "76",
    "Bell's/Kalamazoo Double Cream Stout" : "77",
    "Bell's/Kalamazoo Third Coast Old Ale" : "78",
    "Bell's/Kalamazoo Expedition Stout" : "79",
    "Bell's/Kalamazoo Best Brown Ale" : "80",
    "Bell's/Kalamazoo Cherry Stout" : "81",
    "Blue Moon Blue Moon White" : "82",
    "Breckenridge Avalanche Amber" : "83",
    "Breckenridge Autumn Ale" : "84",
    "Breckenridge Pale Ale" : "85",
    "Breckenridge Christmas Ale" : "86",
    "Breckenridge Oatmeal Stout" : "87",
    "Breckenridge Pandora's Bock" : "88",
    "BridgePort IPA" : "89",
    "BridgePort Porter" : "90",
    "BridgePort ESB" : "91",
    "BridgePort Black Strap Stout" : "92",
    "BridgePort Blue Heron" : "93",
    "BridgePort Pintail Ale" : "94",
    "BridgePort Ebenezer Ale" : "95",
    "BridgePort Old Knucklehead" : "96",
    "Budweiser (U.S)" : "97",
    "Budweiser Bud Light" : "98",
    "Budweiser Bud Ice" : "99",
    "Budweiser Bud Ice Light" : "100",
    "Budweiser Budvar Budvar" : "101",
    "Busch" : "102",
    "Busch Light" : "103",
    "Busch Ice" : "104",
    "Clausthaler" : "105",
    "Colt 45 Malt Liquor" : "106",
    "Coors Original" : "107",
    "Coors Light" : "108",
    "Coors Extra Gold" : "109",
    "Corona Light" : "110",
    "Corona Extra" : "111",
    "Czechvar" : "112",
    "Deschutes Cascade Ale" : "113",
    "Deschutes Mirror Pond Pale" : "114",
    "Deschutes Bachelor ESB" : "115",
    "Deschutes Black Butte Porter" : "116",
    "Deschutes Quail Springs IPA" : "117",
    "Deschutes Obsidian Stout" : "118",
    "Deschutes Jubelale" : "119",
    "Deschutes Broken Top Bock" : "120",
    "Deschutes Pine Mountain Pils" : "121",
    "Deschutes Cinder Cone Red" : "122",
    "Dos Equis Dos Equis XX" : "123",
    "Dragon Stout Dragon Stout" : "124",
    "Edison Light Edison Light" : "125",
    "Foster's Lager" : "126",
    "Fuller's ESB" : "127",
    "Fuller's London Pride" : "128",
    "Genessee 12 Horse" : "129",
    "Genessee/High Falls Genny Light" : "130",
    "Genessee/High Falls Kipling Light Lager" : "131",
    "Grolsch" : "132",
    "Gordon Biersch Marzen" : "133",
    "Gordon Biersch Blonde Bock" : "134",
    "Gordon Biersch Pilsner" : "135",
    "Guinness Guinness Draught" : "136",
    "Guinness Foreign Extra Stout" : "137",
    "Hamm's" : "138",
    "Hamm's Light" : "139",
    "Heineken" : "140",
    "Henry Weinhard's Ale" : "141",
    "Henry Weinhard's Amber Ale" : "142",
    "Henry Weinhard's Dark" : "143",
    "Henry Weinhard's Hefeweizen" : "144",
    "Henry Private Reserve" : "145",
    "Hoegaarden" : "146",
    "Icehouse 5.0" : "147",
    "Icehouse 5.5" : "148",
    "J.W. Dundee Honey Brown" : "149",
    "Keystone Light" : "150",
    "Kilarney's Red Lager" : "151",
    "Killian's" : "152",
    "Labatt Blue" : "153",
    "Lowenbrau" : "154",
    "Marin Brewing Mt. Tam Pale Ale" : "155",
    "Marin Brewing Bluebeery Ale" : "156",
    "Marin Brewing Albion Amber" : "157",
    "Marin Brewing Marin Weiss" : "158",
    "Marin Brewing Point Reyes Porter" : "159",
    "Marin Brewing Breakout Stout" : "160",
    "Marin Brewing Old Dipsea Barleywine" : "161",
    "Marin Brewing India Pale Ale" : "162",
    "McMenamins Hammerhead" : "163",
    "McMenamins Terminator" : "164",
    "McMenamins Ruby" : "165",
    "McMenamins Black Rabbit Porter" : "166",
    "McMenamins Dry Irish Stout" : "167",
    "Michelob" : "168",
    "Michelob Light" : "169",
    "Michelob Amber Bock" : "170",
    "Michelob Hefeweizen" : "171",
    "Michelob Honey Lager" : "172",
    "Michelob Black & Tan" : "173",
    "Michelob Ultra" : "174",
    "Mickey's" : "175",
    "Mickey's Ice" : "176",
    "Miller Genuine Draft" : "177",
    "Miller Genuine Draft Lite" : "178",
    "Miller High Life" : "179",
    "Miller Lite" : "180",
    "Moosehead" : "181",
    "Murphy's Irish Red" : "182",
    "Murphy's Stout" : "183",
    "O'Douls" : "184",
    "O'Douls Amber" : "185",
    "Odell's 90 Shilling" : "186",
    "Odell's Easy Street Wheat" : "187",
    "Odell's Cutthroat Porter" : "188",
    "Odell's Cutthroat Pale Ale" : "189",
    "Odell's Levity" : "190",
    "Odell's Isolation" : "191",
    "Odell's Bobby" : "192",
    "Olde English 800" : "193",
    "Olde English 800 Ice" : "194",
    "Old Milwaukee" : "195",
    "Pabst Blue Ribbon" : "196",
    "Paulaner Original Munich" : "197",
    "Paulaner Salvator" : "198",
    "Paulaner Hefe-Weizen" : "199",
    "Pete's Brewing Wicked Ale" : "200",
    "Pete's Brewing Oktoberfest" : "201",
    "Pete's Brewing Summer Brew" : "202",
    "Pete's Brewing Winter Brew" : "203",
    "Pete's Brewing Helles Lager" : "204",
    "Pete's Brewing Red Rush" : "205",
    "Pete's Brewing Strawberry Blonde" : "206",
    "Pilsner Uruqell" : "207",
    "Pittsburgh Brewing I.C. Light" : "208",
    "Pittsburgh Brewing Iron City Lager" : "209",
    "Pyramid Hefeweizen" : "210",
    "Pyramid Coastline Pilsner" : "211",
    "Pyramid Apricot Ale" : "212",
    "Pyramid India Pale Ale" : "213",
    "Pyramid Pale Ale" : "214",
    "Pyramid Curve Ball Kolsch" : "215",
    "Pyramid Broken Rake" : "216",
    "Pyramid Tilted Kilt" : "217",
    "Pyramid Snow Cap Ale" : "218",
    "Red Dog" : "219",
    "Redhook ESB" : "220",
    "Redhook IPA" : "221",
    "Redhook Blonde Ale" : "222",
    "Redhook Hefe-weizen" : "223",
    "Redhook Nut Brown" : "224",
    "Rhinebecker" : "225",
    "St. Pauli Girl" : "226",
    "St. Pauli Girl Dark" : "227",
    "St. Pauli Girl N.A." : "228",
    "Sam Adams Light" : "229",
    "Sam Adams Boston Lager" : "230",
    "Sam Adams Golden Pilsner" : "231",
    "Sam Adams Cream Stout" : "232",
    "Sam Adams Boston Ale" : "233",
    "Sam Adams Cherry Wheat" : "234",
    "Sam Adams Spring Ale" : "235",
    "Sam Adams Summer Ale" : "236",
    "Sam Adams Pale Ale" : "237",
    "Sam Adams Octoberfest" : "238",
    "Sam Adams IPA" : "239",
    "Sam Adams Winter Lager" : "240",
    "Sam Adams Double Bock" : "241",
    "Sam Adams Triple Bock" : "242",
    "Sapporo" : "243",
    "Shiner Bock" : "244",
    "Shiner Light" : "245",
    "Sierra Nevada Pale Ale" : "246",
    "Sierra Nevada Porter" : "247",
    "Sierra Nevada Stout" : "248",
    "Sierra Nevada Wheat" : "249",
    "Sierra Nevada Summerfest" : "250",
    "Sierra Nevada Celebration" : "251",
    "Sierra Nevada Bigfoot" : "252",
    "Stone Brewing Arrogant Bastard Ale" : "253",
    "Stone Brewing Stone Pale Ale" : "254",
    "Stone Brewing Stone Smoked Porter" : "255",
    "Stone Brewing Stone IPA" : "256",
    "Stone Brewing Ruination IPA" : "257",
    "Stone Brewing Double Bastard Ale" : "258",
    "Stone Brewing Stone Old Guardian" : "259",
    "Tsingtao" : "260",
    "Widmer Hefeweizen" : "261",
    "Widmer Pale Ale" : "262",
    "Widmer Blonde Ale" : "263",
    "Widmer Widberry" : "264",
    "Widmer Sommerbra" : "265",
    "Widmer Oktoberfest" : "266",
    "Widmer Winternacht" : "267",
    "Widmer Spring Run IPA" : "268",
    "Widmer Drop Top Amber Ale" : "269",
    "Yuengling Premium" : "270",
    "Yuengling Light" : "271",
    "Yuengling Ale" : "272",
    "Yuengling Porter" : "273",
    "Yuengling Lager" : "274",
    "Yuengling Black & Tan" : "275",
    "Yuengling Light Lager" : "276"
  }
})

beverage_codes = utils.gen.InsensitivePreservingDict()
for category in beverages.keys():
  beverage_codes.update(beverages[category])
  
unit_codes = utils.gen.InsensitivePreservingDict({ 'lbs' : '0', 'lb' : '0', 'kg' : '1' })

gender_codes = utils.gen.InsensitivePreservingDict({ 'male' : '0', 'm' : '0', 'female' : '1', 'f' : '1' })
