# encoding: utf-8
"""
kombat.py

Created by Michael B. Klein on 2008-03-14.
Copyright (c) 2008 __MyCompanyName__. All rights reserved.
"""

import sys
import os
import supybot.utils as utils

moves_data = { 'I': { 'johnny_cage': { 'green_flame': 'B,F,B,LP',
                                  'split_punch': 'D+HK',
                                  'shadow_kick': 'B,F,LK',
                                  'fatality': 'F,F,F,LP' },
                 'rayden':      { 'lightning_throw': 'B,D,F,LP',
                                  'torpedo': 'B,B,F',
                                  'teleport': 'D,D,U',
                                  'fatality': 'F,B,B,B,LP' },
                 'kano':        { 'cannonball': 'BL,F,D,B,U,F',
                                  'knife': 'Hold BL,B,F',
                                  'shadow_kick': 'B,F,LK',
                                  'fatality': 'Hold BL,B,B,LP' },
                 'liu_kang':    { 'fireball': 'F,F,LP',
                                  'flying_kick': 'F,F,HK',
                                  'fatality': 'Hold BL,F,D,B,U,F' },
                 'scorpion':    { 'harpoon': 'B,B,LP',
                                  'teleport': 'D,B,LP',
                                  'fatality': 'Hold BL,U,U' },
                 'sonya_blade': { 'freeze': 'B,D,F,LP',
                                  'slide': 'B+LK+HK',
                                  'fatality': 'F,D,F,LP' },
                 'sub_zero':    { 'ring_toss': 'Hold LP,B',
                                  'square_wave_flight': 'F,B,LP',
                                  'scissor_grab': 'D,LP+LK',
                                  'fatality': 'F,F,B,B,BL' } },
                  'II': { 'reptile':  { 'invisibility': 'Hold BL,U,U,D,Release BL,HP',
                                  'force_ball': 'B,B,HP+LP',
                                  'acid_spit': 'F,F,HP',
                                  'slide': 'B+LK+HK',
                                  'fatalities': { 'pit_fatality': 'D,D,F,F,BL',
                                  'friendship': 'B.B.D.LK',
                                  'babality': 'D,D,B,B,LK',
                                  'slient_kill': 'Become invisible,F,F,D,HK (close)',
                                  'decap': 'B,B,D,LP (half screen)' } },
                  'scorpion':   { 'teleport': 'D,B,HP',
                                  'harpoon': 'B,B,LP',
                                  'leg_takedown': 'F,D,B,LK',
                                  'air_throw': 'BL in air',
                                  'fatalities': { 'toasty!': 'D,D,U,U,HP',
                                  'pit_fatality': 'D,F,F,BL',
                                  'friendship': 'B,B,D,HK',
                                  'babality': 'D,B,B,HK',
                                  'double_slice': 'Hold HP,F,D,F,F,F (close)',
                                  'incinerate': 'U,U,HP (half screen)' } },
                  'jax':        { 'energy_wave': 'F,D,B,HK',
                                  'multiple_throw': 'F+LP,Rapid HP',
                                  'gotcha_grab': 'F,F,LP,Rapid LP',
                                  'fatalities': { 'arm_rip': 'BL,BL,BL,BL,LP (sweeping distance)',
                                  'head_crusher': 'Hold LP,F,F,F,release (sweeping distance)',
                                  'pit_fatality': 'U,U,D,LK',
                                  'friendship': 'D,D,U,U,LK',
                                  'babality': 'D,U,D,U,LK' },
                                  'backbreaker': 'BL in air',
                                  'ground_pound': 'Charge LK 3 seconds',
                                  'overhead_hammer': 'F+HP' },
                  'mileena':    { 'roll': 'B,B,D,HK',
                                  'teleport': 'F,F,LK',
                                  'sai_throw': 'Charge HP 2 seconds',
                                  'fatalities': { 'pit_fatality': 'F,D,F,LK',
                                  'friendship': 'D,D,D,U,HK',
                                  'babality': 'D,D,D,HK',
                                  'man-eater': 'Charge HK 3 seconds (close)',
                                  'sais_of_death': 'F,B,F,LP (close)' } },
                  'baraka':     { 'spark_toss': 'D,B,HP',
                                  'slice': 'B+HP',
                                  'fatalities': { 'pit_fatality': 'F,F,D,HK',
                                  'friendship': 'U,F,F,HK',
                                  'babality': 'F,F,F,HK',
                                  'decap': 'B,B,B',
                                  'impale': 'B,F,D,F,LP (close)' },
                                  'shredder': 'B,B,B,LP' },
                  'liu_kang':   { 'flying_kick': 'F,F,HK',
                                  'high_fire': 'F,F,HP',
                                  'low_fire': 'F,F,LP',
                                  'bicycle_kick': 'Charge LK 4 seconds',
                                  'fatalities': { 'pit_fatality': 'B,F,F,LK',
                                  'friendship': 'F,B,B,B,LK',
                                  'babality': 'D,D,F,B,LK',
                                  'shaolin_dragon': 'D,F,B,B,HK (close)',
                                  'cartwheel': 'F,U,B,D,F' } },
                  'johnny_cage':{ 'low_bolt': 'B,D,F,LP',
                                  'high_bolt': 'F,D,B,HP',
                                  'fatalities': { 'pit_fatality': 'D,D,D,HK',
                                  'friendship': 'D,D,D,HK',
                                  'babality': 'B,B,B,HK',
                                  'triple_decap': 'Do decap,D+LK+BL+LP',
                                  'rip_in_half': 'D,D,F,F,LP (close)',
                                  'decap': 'F,F,D,U (close)' },
                                  'split_punch': 'LP+BL',
                                  'shadow_kick': 'B,F,LK',
                                  'shadow_uppercut': 'B,D,B,HP',
                                  'gym_kick': 'F+LK' },
                  'sub_zero':   { 'ground_freeze': 'D,B,LK',
                                  'freeze': 'D,F,LP',
                                  'slide': 'B+LK+HK',
                                  'fatalities': { 'freeze_uppercut': 'F,F,D,HK (sweeping distance)... F,D,F,F,HP(close)',
                                  'ice_gernade': 'Hold LP,B,B,D,F,Release (Full screen)',
                                  'pit_fatality': 'D,F,F,BL',
                                  'friendship': 'B,B,D,HK',
                                  'babality': 'D,B,B,HK' } },
                  'rayden':     { 'teleport': 'D,U',
                                  'torpedo': 'B,B,F',
                                  'shock_grasp': 'Charge HP 3 seconds',
                                  'fatalities': { 'pit_fatality': 'U,U,U,HP',
                                  'friendship': 'D,B,F,HK',
                                  'babality': 'D,D,U,HK',
                                  'super_uppercut': 'Charge HP 7 seconds (close)',
                                  'electrocution': 'Charge LK 5 seconds,Rapid LK+BL (close)' },
                                  'lightning_bolt': 'D,F,LP' },
                  'kitana':     { 'fan_throw': 'F,F,HP+LP',
                                  'fan_lift': 'B,B,B,HP',
                                  'fan_slice': 'B+HP',
                                  'fatalities': { 'pit_fatality': 'F,D,F',
                                  'friendship': 'D,D,D,U,LK',
                                  'babality': 'D,D,D,LK',
                                  'decap': 'BL,BL,BL,HK (close)',
                                  'kiss_of_death': 'Hold LK,F,F,D,F,release (close)' },
                                  'zip_punch': 'F,D,B,HP' },
                  'kung_lao':   { 'teleport': 'D,U',
                                  'spin': 'Hold BL,U,U,Release BL,Rapid LK',
                                  'hat_throw': 'B,F,LP',
                                  'fatalities': { 'pit_fatality': 'F,F,F,HP',
                                  'friendship': 'B,B,B,D,HK',
                                  'babality': 'B,B,F,F,HK',
                                  'hat_split': 'F,F,F,LK (sweeping distance)',
                                  'decap': 'Hold LP,B,F' },
                                  'hammer_kick': 'D+HK in air' },
                  'shang_tsung':{ 'morph': { 'scorpion': 'Hold BL,U,U',
                                  'reptile': 'Hold BL,U,D,release,HP',
                                  'jax': 'D,F,B,HK',
                                  'mileena': 'Charge HP 2 seconds',
                                  'baraka': 'D,D,LK',
                                  'liu_kang': 'B,F,F,BL',
                                  'johnny_cage': 'B,B,D,LP',
                                  'rayden': 'D,B,F,LK',
                                  'sub_zero': 'F,D,F,HP',
                                  'kitana': 'BL,BL,BL',
                                  'kung_lao': 'B,D,B,HK' },
                                  'three_flaming_skulls': 'B,B,F,F,HP',
                                  'two_flaming_skulls': 'B,B,F,HP',
                                  'fatalities': { 'pit_fatality': 'Hold BL,D,D,U,release,D',
                                  'kintaro_morph': 'Charge LP 25 seconds',
                                  'friendship': 'B,B,D,F,HK',
                                  'babality': 'B,F,D,HK',
                                  'soul_stealer': 'U,D,U,LK (close)',
                                  'death_from_within': 'Charge HK 3 seconds (sweeping distance)' },
                                  'one_flaming_skull': 'B,B,HP' } } }#,
#               'III': { 'cyrax': {},
#                 'jax': {},
#                 'kabal': {},
#                 'kano': {},
#                 'kung_lao': {},
#                 'liu_kang': {},
#                 'nightwolf': {},
#                 'sektor': {},
#                 'shang_tsung': {},
#                 'sheeva': {},
#                 'sindel': {},
#                 'sonya_blade': {},
#                 'stryker': {},
#                 'sub_zero': {},
#                 'smoke': {} } }
