[
 "Aladdin's Lamp", 
 "All American", 
 "Amazing Fountain (Ass\u2122t of 4)", 
 "America", 
 "American Jubilee", 
 "American Spirit (The)", 
 "Americana Candle Ammo Gas/Mustard gas Anaconda FTN", 
 "Angel Samba Ft", 
 "Apache Firedance Ftn* Around The World Asteroids Attack Vehicle Aurora Borealis Autumn Chrysanthemum Baby Magic Blooms (Crazy Jacks) Barrel of Fun Battle Smoke Battle Star Fountain", 
 "Battle Tank (M-1 Tank w/spray)", 
 "Bee Hive", 
 "Bengal Fountain", 
 "Bermuda Triangle", 
 "Beyond 2000", 
 "Beyond 2000", 
 "Big Bad Mudder", 
 "Big Beautiful FTN", 
 "Big City Lights", 
 "Big Fountain 6\ufb02", 
 "Big Gold", 
 "Big Kahuna", 
 "Big Silver", 
 "Big Sky", 
 "Billionaire Goes Bonkers", 
 "Bird Cage", 
 "Birthday Cake Large", 
 "Birthday Cake Small", 
 "Bizarre FTN", 
 "Black Gold", 
 "Black Night", 
 "Black Out", 
 "Black Phantom Smoke", 
 "Black Snake", 
 "Black Widow", 
 "Blaster Ball (Hand Blaster)", 
 "Blast-off Fountain", 
 "Blast-O-Maniac", 
 "Blazing Rebel Blistering Sky Blossoming Flowers FTN", 
 "Blossoming Magic Candle", 
 "Blossoming Plum FTN Blue Ammo Smoke", 
 "Blue Cats Blue Frost Blue Millennium", 
 "Blue Planet FTN Blue Stars Boat Load Of Color Bold and Beautiful Boomer", 
 "Bouquet Ftn", 
 "Brachiosaurus", 
 "Breathless", 
 "Bumper Cars", 
 "Butterflies & Flowers Blue", 
 "Butterflies & Flowers Gold", 
 "Butterflies & Flowers Green", 
 "Butterflies & Flowers Red", 
 "Butterflies Large Fountain", 
 "Butterfly & Flowers Large", 
 "Butterfly & Flowers Small", 
 "Butterfly & Silver Flower Butterfly Flowers California Candle 14\ufb02 California Candle 18\ufb02", 
 "California Candle Jumbo", 
 "California Condor California Dreaming California Gold Rush California Rocket FTN", 
 "Camellia Flower Large California Sunrise Camellia Flower Small Cannon Smoke", 
 "Careless In California", 
 "Carnival Fountain", 
 "Century 21 FTN", 
 "Champagne Popper 6 Pack/Single", 
 "Changing Color FTN", 
 "Checkered Flag", 
 "Cherry and Lemon Tree", 
 "Cherry Blossom", 
 "Chinese Brilliant FTN", 
 "Christmas Eve FTN", 
 "Chrysanthemum", 
 "Cigar Smoke", 
 "Circus Fireworks", 
 "Classic Fountain Maximum Load", 
 "Conch Fireworks (Box 6)", 
 "Conic Cone 6\ufb02 (Color Changing)", 
 "Conic Cones, #1 #2 & #3", 
 "Conic Fountain Conic FTN Cool", 
 "Cosmic Hail Cracker Bombs Cracking Ground Bloom Cracking Strobe Light Crackle & Sparkle Crackles", 
 "Crackling Ball", 
 "Crackling Cactus", 
 "Crackling Flare Crackling ground Bloom Crackling Jumping Jacks Crackling Strobe Pot", 
 "Crackling Tree", 
 "Crackling Whip 10\ufb02", 
 "Crackling Whip Super 10\ufb02", 
 "Crazy Bugs", 
 "Crazy Eyeballs", 
 "Crazy Ground Hog", 
 "Crazy Jacks (Baby Magic Blooms)", 
 "Crazy Monster", 
 "Crickets", 
 "Cristhanimum Flower Crystal FTN Cuckoo", 
 "Cuckoo Assorted Fountain", 
 "Cuckoo Jr.", 
 "Cuckoo Jr. (18 coz/cs)", 
 "Dancing Butterflies", 
 "Dancing Cat", 
 "Dancing Devil", 
 "Desert Blitz Desert Blitz Desert Smoke Desert Sun", 
 "Devil Dancer", 
 "Devil Delight", 
 "Devil Ray", 
 "Diamond Cutter", 
 "Diamonds Forever", 
 "Dinosaurs Fountain (Ass\u2122t of 3)", 
 "Disco Flash Dixie Delight Dizzy Demon Spinner", 
 "Double Eagle FTN", 
 "Dragon Blaster", 
 "Dragon Boat", 
 "Dragon Breath Dragon China Dragon Ear Dragon Quest", 
 "Dragon Slayer Dragon Spit Fire Dragon Wrath Dragons Tears Dust Devil Jumbo Cone Eagle FTN.", 
 "Eagle Wing", 
 "Eclipse FTN Electric Rainbow Electrical Shock", 
 "Emerald Illusions EA418 Euphony", 
 "Exhibition The FTN", 
 "Fantastic FTN Far Out Feast Of Fire Festival Happiness Fiery Dragon", 
 "Fiery Echo", 
 "Fiery Fiesta", 
 "Fiesta Smoke Balls", 
 "Fiesta Sparklers", 
 "Fighting Force Fountain", 
 "Finale Fountain", 
 "Fine Champagne", 
 "Fire Breathing Dragon", 
 "Fire Cracker FTN Fire Engine Fire Fly FTN Fire in the Sky FTN", 
 "Fire Krackle", 
 "Fire Storm", 
 "Flaming Arrow Torch", 
 "Flash Ray Gun", 
 "Flashing Signal, Black Cat (Strobe)", 
 "Flashing Wheel", 
 "Flashtron FTN Flower Power", 
 "Fountain of Glory Fountain of Joy", 
 "Four Color 1\ufb02 Ftn", 
 "Four Performances (Square)", 
 "Freedom Assorted Fountains Friendship Flower Friendship Flower Small Friendship Fountain Large", 
 "Friendship Pagoda", 
 "Frog", 
 "Funny Car", 
 "Galactic Stardust Garantua FTN Garden of Eden", 
 "Garden Party", 
 "Gator FTN", 
 "Gator Whistle", 
 "Georgia Peach Fountain", 
 "Giant Beehive", 
 "Giant Brilliant", 
 "Giant Devil", 
 "Giant Genie Giant Mystery Geyser Giant Smoking Genie Cone Giant Tiger Cone #4", 
 "Gila Monster", 
 "Glitter Cones Color Glitter", 
 "Glitter Cones Crackling Glitter", 
 "Glitter Cones Gold Glitter", 
 "Glitter Cones Silver Glitter", 
 "Glittering Flower", 
 "Glittering Fountain Glittering Gems FTN Globe Glorious Dream", 
 "Glorious Flower", 
 "Glow Worm (Snakes)", 
 "Going Fast in Georgia", 
 "Gold", 
 "Gold Bar FTN", 
 "Gold Crown Royal", 
 "Gold Rush EA416", 
 "Gold Rush EA420", 
 "Gold Rush EA424", 
 "Gold Rush Fountain Gold Star Gold Star& Crackling Star Golden Angels Golden Dawn Golden Diamond Golden Dragon Golden Fan Golden Fish Golden Flower Golden Flower Large Golden Flower Small", 
 "Golden Flowers Blossom", 
 "Golden Gate Spectacular", 
 "Golden Glittering Flower", 
 "Golden Goose", 
 "Golden Leaves", 
 "Golden Palace Golden Pine Forest Golden Shower Large Golden Shower Small", 
 "Golden Zia Gold-Silver Flower", 
 "Grand Celebration Grand Illusion Grand Prix Race Car Great Wall", 
 "Great White", 
 "Great White Smoke FTNG", 
 "Green", 
 "Green Cracker Ball", 
 "Green Glittering Flower", 
 "Green Jade", 
 "Green Lightning", 
 "Green Willow", 
 "Green Willow 5\" Fountain", 
 "Ground Blaster", 
 "Ground Bloom Flowers", 
 "Ground Covered with Red Light", 
 "Gyro Bloom Hail Hammer Head Shark", 
 "Hand Blaster (Blaster Balls)", 
 "Hand Grenade Smoke", 
 "Happiness", 
 "Happy Bird", 
 "Happy Birthday Large", 
 "Happy Birthday Small Happy Festival Happy Festival Fountain Happy Lamp Large", 
 "Happy Lamp Small", 
 "Happy Lion", 
 "Happy Silver Flowers", 
 "Happy Sound", 
 "Hatfield and McCoys Havana Heat", 
 "Hawaiian Delight Hawaiian Rainbow", 
 "Hawk FTN Hearts A Fire", 
 "High Sierra Showdown High Tower Highway to Heaven", 
 "Hissing Cobra Ftn * Hollywood Nights Hornets Hot Pots Hot Rod Hot Shot Houdini FTN", 
 "Howling Coyote Fountain", 
 "Humming Bird FTN", 
 "Hurricane", 
 "Hyper 8 Race Car", 
 "Iguanaman FTN", 
 "Independence", 
 "India Magic", 
 "Indy Car", 
 "Inferno", 
 "Instant happiness", 
 "Jack in the Box Jade Flower Jade Flower Fountain Large Jade Flower Fountain Medium", 
 "Jade Flower Fountain Small", 
 "Jades of Green", 
 "Jidder Bug FTN", 
 "Jubilation FTN Jumbo California Candle Jumbo Carnival Jumbo Magnum Popper", 
 "Jumping Cat Large", 
 "Jumping Cat Small", 
 "Jumping Jack", 
 "Jumping Wheel", 
 "June Bug FTN", 
 "Jungle King", 
 "Jurassic Paradise Fountain Just Another Stinkin Ftn Kahuna\u2122s Revenge Kamikaze Attack", 
 "Killer Bees", 
 "King Crab", 
 "King Kong Fountain", 
 "King Neptune Party", 
 "King of Hearts", 
 "Krakatoa Fountain Lady Bug Lady Liberty", 
 "Large Fountain, Tri-Color, Large", 
 "Large Night Howler", 
 "Large Night Siren Laser Blazer Laser Dragon Laser Master Lava Lamp Lava Smoke FTN Liberty Torch (hand held)", 
 "Lighthouse Fountain", 
 "Lightning Bolt", 
 "Lightning Charged", 
 "Lightning Flash", 
 "Lightning Flashes (Strobe)", 
 "Lil Patriot", 
 "Livewire", 
 "Locomotive Breath", 
 "Lost City FTN", 
 "Lotus #2", 
 "Lotus #3/Spinner", 
 "Luck of the Irish", 
 "Lucky Leprachaun", 
 "Lucky Seven M-45 Tank M-80 Smoker (Ozark Smoke)", 
 "Mach III", 
 "Mad Dog", 
 "Madhatter FTN", 
 "Magic Ball", 
 "Magic Black Snakes", 
 "Magic Blooms Magic Horseshoe Magic Mountain Magic Whip 10\ufb02 Magic Whip 30", 
 "Magnum Pistol Poppers", 
 "Magnum Reloadable Ftn", 
 "Majaestic Rainbow", 
 "Mako Shark Malibu Madness Mammoth Fountain Mammoth Smoke/Military Smoke", 
 "Mammoth Wheel", 
 "Mandarin Duck", 
 "Mars FTN", 
 "Martian greeting", 
 "Masterpiece", 
 "Medieval Delight Fountain", 
 "Medieval Fantasy Fountain", 
 "Midas Touch", 
 "Mighty Dragon", 
 "Mighty Twirler", 
 "Millennium 2000", 
 "Millennium Madness FTN", 
 "Mini Barrel", 
 "Mini Bomb Snapper", 
 "Mini Cuckoo Fountain", 
 "Mini Geyser Fountain Mini Me Mini Monster Mini Pyro", 
 "Miss liberty", 
 "Missile War", 
 "Monarch of the Forest", 
 "Mongolian Campfire", 
 "Monkey Drive", 
 "Monkey Sound", 
 "Monoclonius", 
 "Monster Blast", 
 "Monster Buster", 
 "Monster Magic Whip (Box 3)", 
 "Monster Parade", 
 "Monster Party Poppers (Bag", 
 "6)", 
 "Monster Snaps Monster tractor Pull Monster Truck Moon Dance", 
 "Morning Glory", 
 "Morning Glory", 
 "Morning Glory (Sparklers)", 
 "Morning Glory 14\ufb02", 
 "Mortar Fire FTN", 
 "Mother Nature", 
 "Mount Etna", 
 "Mountain Springs Waterfall", 
 "Mr. Turtle", 
 "Musical Pyramid", 
 "Mustard Gas", 
 "Mystery Geyser", 
 "Navigation 1\ufb02 FTN", 
 "Never Forget", 
 "New Age Madness", 
 "New Moon", 
 "New York Harbor Ftn", 
 "Niagara Falls", 
 "Niagara Falls Jumbo", 
 "Night Heat", 
 "Night Howler", 
 "Night Howler, Large Night Lights Night Rider Night Treasure", 
 "Night Works Fountain Nite Siren Whistle", 
 "Nova", 
 "Nuclear Meltdown Nuke Power Nutty Monkey Ocean Moon Odyssey Odyssey FTN OHH Soo Good Old Faithful Old Glory", 
 "Old Town Express", 
 "Old West Express", 
 "Opening Flower Happy Bird Outer Limits Pacific Paradise", 
 "Painted Desert Palm Tree/Snow Flake (Asstd) Patriotic Power Blast Peace Keepers Peach Flower Peach Flower in Spring Peach Flower in Spring Peacock Fountain #1 Peacock Fountain #2", 
 "Peacock Fountain #3", 
 "Peacocks Tail Fountain", 
 "Pearls of the Orient", 
 "Pegasus Fountain", 
 "Petal to the Metal in Pennsylvania", 
 "Phantasmic Ftn *", 
 "Phantastics Finale Phantom Blast Phantom Finale", 
 "Phantom Fire", 
 "Phantom Ftn", 
 "Phantom Furry", 
 "Phantom Large FTN", 
 "Phantom Power FTN Phantom Stampede", 
 "Phantom Wheel Phoenix Tail Howl, Large", 
 "Phoenix Tail Howl, Small", 
 "Phoenix Tail/Whistling Dixie", 
 "Piccolo Pete (Whistle Pete)", 
 "Picnic Basket", 
 "Picturesque Trigon", 
 "Pistol Popper", 
 "Pixie Dust", 
 "Platinum and Cold Ftn", 
 "Plum Flowers Report Spring, Large", 
 "Plum Flowers Report Spring, Small Poco Diablos Police Cars Pop-Its TNT", 
 "Pot of Gold", 
 "Powder Keg Power Flash Power Fountain Power Surge", 
 "Precious Stones", 
 "Prehistoric Eruption Fountain", 
 "Premier Performance", 
 "Pulling Fireworks", 
 "Purple Orchid", 
 "Purple Pearl", 
 "Purple Rain", 
 "Purple Rain Candle", 
 "Pyramid", 
 "Pyro Marathon Pyro Perfection", 
 "Pyro Pete Quake the Big One", 
 "Queen of Hearts Quiet Riot Racing Car Raging Bull", 
 "Raging Ghoul", 
 "Raging Monster", 
 "Rain Dance", 
 "Rainbow Fire", 
 "Rainbow Fountain", 
 "Rainbow Surprise", 
 "Rainbow Wheel", 
 "Rat TAT TAT TAT FTN", 
 "Rattlesnake 14\"", 
 "Razzel Dazzle Large", 
 "Razzel Dazzle Medium", 
 "Red", 
 "Red Begonia", 
 "Red Devil Reloadable FTN", 
 "Red Snow Plum Ft.", 
 "Reloadable FTN", 
 "Reloadable Smoke", 
 "Remember", 
 "Rising Flag", 
 "Rising Sun Fountain Road Queen Rocket Gun", 
 "Rocket Man", 
 "Rocking In The U.S.A. Rocky Mountain High Rocky Mountain Stream FTN Rocky Road", 
 "Rose Blossom", 
 "Rotating Wheel", 
 "Royal Flush", 
 "Rubys & Emeralds", 
 "Saphire & Gold", 
 "Screamer Ftn", 
 "Screaming Demon", 
 "Screaming Ghoul", 
 "Screaming Tiger Screaming Willy", 
 "Screech and Scream Screecher Pack", 
 "Screeching Turbo Racer", 
 "See You Later Alligator Seventh Heaven Shark Attach Shimmering Dream Fountain", 
 "Shiny Gadget", 
 "Shogun FTN", 
 "Shoot the Moon Show Time Show Time Smoke", 
 "Showtime Mini Smoke", 
 "Silver Silver Bubbles", 
 "Silver Chrysanthemum", 
 "Silver Fan", 
 "Silver Glittering No. 1", 
 "Silver Orchid", 
 "Silver Salute", 
 "Silver Spangler Silver Star Silvery Chrysanthemum (Handle) Silvery Flowers Fountain", 
 "Silvery Glittering Fountain #1", 
 "Silvery Water Fountain (Pyramid)", 
 "Sizzler", 
 "Sky Flash Sky Parade Skyline Skyline FTN", 
 "Smoke Balls, Colored", 
 "Smoke Candle Large", 
 "Smoke Candle Small", 
 "Smoke Firecrackers", 
 "Smoke Fountain, Colored Blackcat", 
 "Smoke Grenade", 
 "Smoke Mammoth", 
 "Smoking Cracker", 
 "Smoking Missile", 
 "Smoking Roman Candle", 
 "Smoking Screen", 
 "Smoking Volcano Cone", 
 "Smoky Mountain Stream Fountain", 
 "Snakes (Glow Worms)", 
 "Snappers (Pop Pop) (Snap Kaps) (Drop", 
 "Pops)", 
 "Snow Fall", 
 "Snowflake & Palm Tree", 
 "Soaring Spirit Solar Blaze Solar Capsule", 
 "Solar Flares", 
 "Solar Glare", 
 "Sonic Boom", 
 "Sonic Fireworks", 
 "Sonic Flash", 
 "Sonic Jack Sound Of City Of Albuquerque Sirius blast Southern Nights/Lights Space Invader Spinner", 
 "Space Lamp", 
 "Space Walk Space Wars Spark Plug", 
 "SPARKLERS", 
 "#08 Colored (Night Orchid)", 
 "#08 Gold", 
 "#10 Gold, Colored", 
 "#14 Gold", 
 "#20 Gold", 
 "#36 Gold Sparkling Tree Speedway Racer Spinning Fireball Spinning Jimmy Spinning Ring (ground) Spiral Lite Spirit of America Spirit Spinners", 
 "Spring Greeting", 
 "Spring Peach", 
 "St Elmos Fire", 
 "Stampede Fountain Star Dust EA417 Star Spangled Banner", 
 "Star Sparklers", 
 "Starburst Fountain", 
 "Starfire Fountain", 
 "Starry Starry Night", 
 "Stars & Stripes", 
 "Stars in the Sky Stars Over America Steamboat FTN Steel Rain Stegosaurus Stellar Performance Fountain Sting of the Scorpion Sting of The Scorpion Stinger FTN Stone Cold FTN", 
 "Stones of Treasure", 
 "Stray Beads", 
 "Strobe Bots", 
 "Strobing Pulsar", 
 "Summer Heat", 
 "Sunburst", 
 "Sundance Ftn *", 
 "Sunflower", 
 "Sunlight of Florida", 
 "Sunscaper", 
 "Super Cone", 
 "Super Crackling Whip", 
 "Super Nova", 
 "Super Reb", 
 "Surprise", 
 "Surprise (Sparklers)", 
 "Surround Sound", 
 "Survival Rivals", 
 "Tank (Small) w/stars emits sparks", 
 "Tank M45 Tank With Report Tarantula FTN Tazmanian Devil", 
 "Tea Pot", 
 "Tequila Sunrise", 
 "Texan Giant", 
 "Texas Rider", 
 "Texas Worldwind", 
 "The Great Wall", 
 "The Mighty Dragon", 
 "These Colors Don\u2122t Run", 
 "Thrasher Shark", 
 "Three Colors", 
 "Thunder Over America", 
 "Tidal Wave", 
 "Tiger Fountain 3\ufb02", 
 "Tiger Roarer", 
 "Tiger Shark", 
 "Tiger\u2122s Fury", 
 "Tijuana Tremor Ftn*", 
 "Times 2000 Square", 
 "Titanic", 
 "TNT Barrel TNT Blast TNT Butterfly Fountain TNT Flashing Fountain TNT Flashing FTNS TNT Ftn TNT Lighting Bug Torch of Fire Gold Fire Torch of Fire Silver Fire", 
 "Tortoise", 
 "Tower of Mystery", 
 "Tower of Power Fountain", 
 "Toy Soldier", 
 "Treasure Chest", 
 "Tri-Angle Whistling Flower (Chrysanthemum)", 
 "Tri-Color BC Sunrise Fountain", 
 "Tri-Color Sprayer", 
 "Tri-Color, Small", 
 "Tri-Rotating Wheel", 
 "Tri-Rotating Wheel (Whistling)", 
 "Truck Load", 
 "Turbo Caf\u00e9", 
 "Turbo Flash", 
 "Twin Cone Party Popper", 
 "Twinkle & Dazzle", 
 "Twister FTN", 
 "Tyrannosaurus", 
 "Tyrannosaurus Rex Fountain", 
 "Ultimate Fountain", 
 "Urban Assault Vehicle USA FTN USA Salute FTN Velocity Vesuvius Fountain", 
 "Vienna FTN", 
 "Violet & Butterfly", 
 "Violets and Crimsons", 
 "Volcanic Cavern", 
 "Volcano Cone", 
 "Wailing Witch Fountain", 
 "Warhead Rocket Fountain", 
 "Water Fall FTN Whale Tail Whistle Missile (Musical Pyramid) Whistle Pete (Piccolo Pete)", 
 "Whistling Dixie", 
 "Whistling Fountain 329", 
 "Whistling Gator", 
 "Whistling Phantom * Wild Boar Wild Cat Wild Dancer Wild Fire FTN", 
 "Wine Vase", 
 "Winged Venus Winter Storm Witches Smoke FTN", 
 "Wolf Pack Wonderful Bouquet Wonders of The World Wooosh World of Colors World\u2122s Greatest Fountain", 
 "Wrath Of Hydra Ftn* Yellow Ammo Smoke Yellow Stars Zombies", 
 "3 Times the Charm", 
 "1\ufb02 Fountain, 4-color", 
 "1\ufb02 Fountain, Assorted BC", 
 "5\ufb02 Fountain, Assorted T1611", 
 "7\ufb02 Fountain, Assorted HN89", 
 "9\ufb02 Fountain, Assorted HN90", 
 "9\ufb02 Fountain, Assorted w/sp HN91", 
 "9\ufb02 Fountain, Assorted M09", 
 "#35 Base Fountain", 
 "HN 60 Assortment", 
 "HN 69 Assortment", 
 "HN 89/A003 Assorted Fountains", 
 "THE FOLLOWING SHOULD INCLUDE FIREWORKS FROM THE", 
 "ABOVE LIST ONLY: Assortments:", 
 "CP897B CP1241 TNT", 
 "CP1233 TNT", 
 "CP1238 TNT", 
 "American Pride", 
 "Big Bear", 
 "Big Dog", 
 "Big Timer", 
 "Bonus Fountain Pack", 
 "Bucking Bronco Assort.", 
 "Celebrations #3", 
 "Celestrial Celebration", 
 "Comet Assortment", 
 "Family Assortment By Wholesale", 
 "Fireworks Show", 
 "Fireworks Warehouse", 
 "Grande 49er", 
 "Grand Finale", 
 "Hornet", 
 "Hot Shot", 
 "Independence", 
 "Just For Kids", 
 "Mad Dog", 
 "Minute Man", 
 "Monster Assortment", 
 "Mystical Night #5", 
 "New Yorker", 
 "Premium Millennium 2000", 
 "Patriotic Power Blast", 
 "Pyro Show", 
 "Red Devil", 
 "Screamer Pack", 
 "Showtime Grand Jumbo", 
 "Stinger", 
 "Super Assortment", 
 "Super Bee", 
 "The Warehouse", 
 "Value Fountain Pack", 
 "X-tra TNT", 
 "Pre Packs:", 
 "Big Value Bag", 
 "Big Bomb", 
 "Blockbuster", 
 "Creep Show Assortment", 
 "Deluxe Big Bomb", 
 "Exhibition (Black Box)", 
 "First Choice (American Made)", 
 "Freedom Tray s/s", 
 "Green Tray", 
 "Happy Birthday America", 
 "Lion Tray", 
 "Magnum Party", 
 "Millennium Salute", 
 "Night Thriller", 
 "Parrot Tray", 
 "Patriotic-Small", 
 "Patriotic-Large", 
 "Patriotic-Super", 
 "Phantom Brigade", 
 "Phantom Collection( Excluding", 
 "Roaring Lion)", 
 "Phantom Force", 
 "Phantom Night Fright", 
 "Phantom Spectacular", 
 "Phantom Thunder", 
 "Phantom Zone", 
 "Poly Bag #3 Novelty", 
 "Red Tray", 
 "Rhino Tray", 
 "Rocket Shape (200 pc)(AS23", 
 "Salute to America (Yellow Box)", 
 "Showtime", 
 "Solar Burst Assortment", 
 "Spectacular #1", 
 "Star Burst Pack", 
 "Storm Chaser #1", 
 "Sunscape", 
 "Super Fireworks Show", 
 "Super Nitro Box (AS14)", 
 "The Big One", 
 "Tray Pack Fireworks (AS15) --ok", 
 "Tray Pack Fireworks (AS19)--ok", 
 "Tray Pack Fireworks (AS25)--ok", 
 "Titan Pack Fireworks (AS33)--ok", 
 "Ultra Pack 2", 
 "Variety-Safe & Sane", 
 "Warrior Tray", 
 "White Box, Large & Medium", 
 "Wild Thing", 
 "PY501 Bargain Bag Assortment", 
 "Hulk Assortment S & S", 
 "Nite-Frenzy Assortment S & S", 
 "Wild Time Assortment", 
 "S & S", 
 "Monster Madness Assortment", 
 "PY528 Thriller Assortment", 
 "Rocketman Value Pak", 
 "Super Bonus Pak", 
 "Party Pak", 
 "NEW ON LIST:", 
 "Easy Light Asst. AS08F", 
 "Super Finale Bonus Pk", 
 "Boomer Bag Pack", 
 "TNT Big Timer", 
 "Bargain Bag SS", 
 "TNT Family Fun Bag", 
 "Thunderbolt CP809A", 
 "Giant Cone Ftn", 
 "Pyro Pak CP809A", 
 "Thunder Over America (Phan)", 
 "Dragon Quest", 
 "Night Raider"
]
