from random import randint

class BeckGenerator:
  
  parts = [
    [
      "Obama and his Civilian National Security Force",
      "Government stormstroopers",
      "Radicalized vegans", 
      "There are sushi-eating socialists among us who", 
      "Barack Hussein Obama and his fellow Muslims",
      "Tyrannical tree-huggers",
       "All you need to do is connect the dots to understand that ACORN and Obama's Czars", 
      "Leftist sodomites", 
      "Obama's roving death squads", 
      "Jackbooted government thugs", 
      "I have in my hand a list of godless left-wing sodomites who",    
      "Militant academic elitists", 
      "Climate Nazis", 
      "The goons at ACORN and the Service Employees International Union", 
      "I'm not saying Obama is Hitler, but don't you find it interesting that members of his secret police force", 
      "Blue-helmeted U.N. troops",
      "The real inconvenient truth liberals don't want you to know is that they", 
      "Pot-smoking PETA worshippers",    
      "We are under siege by a parade of militant homosexuals who", 
      "Because Obama is a crypto-Muslim socialist it is reasonable to assume that his oligarchs",
      "The AmeriCorps program is a front for government bureaucrats who", 
      "The liberal media lapdogs don't want you to know they",
      "It's time we ask ourselves why Hollywood liberals", 
      "Al Qaeda is in cahoots with radicalized Maoists at every level of government who", 
       "There are America-hating liberal terrorist sympathizers among us who", 
      "Barack Obama and his Marxist minions", 
      "Harry Reid and his henchmen", 
      "There are crypto-Muslim sleeper agents in every part of the government who", 
      "Here's what's happening America: Tax-hiking liberal socialists", 
      "God-hating liberal secularists", 
      "A lot of Americans aren't paying attention to the fact that the socialists running Congress", 
      "The leftist Al Qaeda conspirators who control Congress", 
      "We are under siege by totalitarian government bureaucrats who",    
      "The Obamanazis occupying the White House", 
      "We must take our country back from the godless socialists who", 
      "The Nazis running the Democrat party", 
      "I'm not saying Obama is the antichrist, but don't you find it suspicious that his foot soldiers",
      "Buckle up your seatbelt, America, and prepare for a crash landing because the liberals piloting your plane",
      "The liberal elites infesting our government",
      "Obama and his Kenyan overlords",
      "The Haiti-helping hippies who work in the White House",
      "Liberal jihadists throughout the Democrat party", 
      "Hollywood elites and their arugula-eating disciples",
      "The terrorist enablers in our Taliban-occupied White House",
      "The pot-smoking special interest groups that control Congress",
      "We are under siege by lesbian environmentalists who",
      "Liberal neo-monarchists",
      "Barack Osama and the radical Islamists controlling our government",
      "The same enemies of freedom who stole the presidential election",
      "There are granola-munching Maoists among us who",
      "I have in my hand a list of left-wing socialist jihadists who",
      "The Obama administration and the illuminati", 
      "The freedom-haters who have infiltrated our government",
      "If we don't act now, we won't be able to stop the dope-smoking Trotskyites who",
      "The mainstream media won't tell you, but government thugs", 
      "Nancy Pelosi and her liberal lackeys", 
      "The bongo-playing potheads running the Federal Reserve",
      "Environmentalist wackos and the pelican lobby",
      "Hemp-growing Marxist fornicators",
      "Soy milk-sipping Green Peace activists",
      "Dolphin-loving food co-op members",
      "There is a disease in America. And the disease is being spread by radical Leninists who",
      "Tonight we must ask ourselves why brainwashed Obamatons"
    ],[
      "are using the same tactics the Nazis did to", 
      "have dispatched their brownshirts to help them",
      "are taking a page right out of Stalin's playbook in order to",
      "want to create a One World Government that will",
      "are preparing to invade your property as part of their plan to",
      "are plotting with terrorists to",
      "stole our country when you weren't looking so they could",
      "are perpetrating an elaborate hoax to",
      "are conspiring with the liberal media to",
      "are using gestapo tactics so they can",
      "are acting on the orders of Keith Olbermann so they can",
      "are copying from Mein Kampf chapter and verse so they can",
      "are practicing maneuvers with black helicopters in order to",
      "are building a secret army to enforce their plan to",
      "are releasing flying monkeys as we speak to help them",
      "are close to realizing their dream of a New World Order that will",
      "are brainwashing you so they can",
      "are operating a secret shadow government whose real agenda is to",
      "are consorting with the Bolsheviks at the Federal Reserve to",
      "have formed a secret society that plans to",
      "are hatching schemes to",
      "are seeking to create a One World Government that will",
      "are forging a secret plot to take over America once they",
      "are trying to create a public panic about global warming so they can",
      "are plotting with underwear bombers to",
      "are building an army of zombies so they can",
      "are seeking to indoctrinate our children as part of their plan to",
      "pose a clear and present danger to the republic because they have a secret plan to",
      "are perverting our culture so they can",
      "have a secret plot to",
      "are conspiring with FEMA so they can",
      "are attempting to stifle all dissent so that they can",
      "have a secret diabolical plan to",
      "won't tell you about their real agenda, which is to",
      "are plotting with the terrorists who attacked us on 9/11 to",
      "are plotting as we speak to",
      "are pushing their extremist agenda to",
      "don't want you to know that their real plan is to",
      "have formed a secret cabal to",
      "are working with our enemies to",
      "should make you fear for your country because they're seeking to",
      "have formed a secret oligarhy that aims to",
      "are trampling on our values so they can",
      "are spying on you at this very moment as part of their agenda to",
      "are recreating Nazi Germany so that they can",
      "are coming after all of us, and won't stop until they",
      "are molesting our Constitution with intent to",
      "are enlisting the aliens from Area 51 so they can",
      "are conspiring to",
      "are creating an army of Dennis Kucinich clones to help them",
      "are meeting behind closed doors with intent to",
      "are seeking emergency powers that will enable them to",
      "are plotting with eugenicists to",
      "want to control every aspect of your life so they can",
      "are sending out Tweets to recruit more followers that will help them",
      "are not denying that they plan to",
      "are raising an army of undead beatniks to help them",
      "are pushing their extremist socialist agenda down your throat so they can",
    ],[
      "steal your organs and leave you lying unconscious in a bathtub.",
      "operate concentration camps right here on American soil.",
      "crash your tea party and make you drink the blood of NASCAR fans.",
      "seize your land through Fannie Mae and Freddie Mac.",
      "control our population by putting sterilants in our drinking water.",
      "stage another moon landing in a Hollywood movie lot.",
      "bring your parakeet before a death panel.",
      "prevent you from worshipping Jesus, which is exactly what the Nazis did to the Jews.",
      "spread their global warming hoax and help Al Gore carry out his Final Solution to eradicate capitalism.",
      "create a One World Government that will enslave us all.",
      "enslave you in FEMA camps. They are coming for you. You're on the list. Everyone is on the list.",
      "remove your appendix and eat it in front of you and your children.",
      "shoot puppies on the White House lawn.",
      "spread swine flu through the money supply.",
      "revive eugenics and create a Master Race of Prius-driving hippie super soldiers.",
      "aid the Communists who want to socialize your Nazism. How do I know this? I educated myself. I went to the library.",
      "bind and shackle all white people. That's how reverse racism works, which is why we must enslave them before they enslave us.",
      "force you out of your home and make you live on a hippie commune.",
      "decorate your house with the artwork of Mussolini.",
      "put you in gay reeducation camps.", 
      "make you work as a bureaucratic slave to government.",
      "euthanize your grandma with a pillow.",
      "feed Tea Partiers to the lions on pay-per-view TV.",
      "tattoo a hammer and sickle on your buttocks.",
      "replace the Stars & Stripes with a big flaming rainbow flag.",
      "raise your taxes to pay for illegal immigrants to get abortions. And we must put together our own militia to stop them.",
      "bring all FOX News hosts before a death panel. And if we don't stop them now, it could happen to you.",
      "turn the Washington Monument into a giant bong.",
      "molest your kitten. And you know who else tried to do that? Hitler.",
      "ban the Bible, which is exactly what Trotsky did during the Mexican Missile Crisis.",
      "douse you with gasoline and set you on fire, just like the Communists tried to do to our Founding Fathers at Iwo Jima.",
      "create alien-human hybrids that will vote Democrat in the next election.",
      "control your mind by brainwashing you with fluoride in your drinking water.",
      "round up all FOX News viewers and put them in MSNBC-run reeducation camps.",
      "pack you into Priuses and take you off to a place to be slaughtered.",
      "use stem cell research to clone even more communist pinko vegans wearing Che Guevara t-shirts.",
      "turn us all into communist slaves, which, as you know, is what Mao was trying to do when he bombed Pearl Harbor.",
      "silence Sarah Palin. And we must put together our own militia to stop them.",
      "create a national security crisis, which they will use as a smokescreen to seize dictatorial power.",
      "euthanize ideological dissidents, just like Franklin Roosevelt did to the Confederates at Bull Run.",
      "ban FOX News. And you know who else tried to do that? Hitler.",
      "build a time machine out of a Prius, which will be used to go back and surrender America to the British.",
      "burn teabaggers at the stake. It's all part of their plan. Burn them all and then buy carbon offsets to make their executions more green-friendly.",
      "eradicate capitalism, just like Saddam Hussein tried to do when he attacked us on 9/11.",
      "prevent patriotic Americans from flying their airplanes into IRS buildings.",
      "build a secret moon bunker where all the Czars will seek refuge after they blow up the Earth.",
      "give all our first-born children to the North Koreans.",
      "take away your guns and leave you defenseless when gay Marxist Muslim illegal immigrants come after you.",
      "grind up death panel victims into organic fertilizer.",
      "give federal bailout money to radical Islamic groups, which, as you know, are plotting to blow up megachurches.",
      "make it legal to pee on the flag of this great nation.",
      "kill and eat children using a recipe copied straight out of 'An Inconvenient Truth.'",
      "put you in a socialist reeducation camp. That's where the road ends, people. With you in a camp, lobotomized, and ready to reelect Obama.",
      "turn your church into a drive-through abortion clinic.",
      "require every man, woman, and child to gay-marry a same-sex partner, specially chosen by a government matrimony panel.",
      "strip us of our God-given right to hate our fellow man.",
      "create internment camps for the elderly, the young, the middle aged, the disabled, and the non-disabled.",
      "ban private property and turn it over to the collective. They don't want it to be We the People anymore. They want it to be We the Pot-Smoking Granny-Euthanizing Marxist Nazi Weasels.",
      "hold drugged-out sex orgies during confirmation proceedings for Supreme Court justices.",
      "turn the U.S. into a province of Iran.",
      "exterminate undesirables under the pretext of providing universal health care, just like Hitler did.",
      "fill the Lincoln Memorial Reflecting Pool with bong water.",
      "develop a sitcom based on the life of Hitler, which will be filmed in the White House at taxpayer expense.",
      "lobotomize all registered Republicans who refuse to turn over their private property to the federal government.",
      "change U.S. currency by putting Al Gore, Michael Moore, and Keith Olbermann on $1, $5 and $14 bills. Add up those numbers and what do you get? 20, which is the same day of the month Hitler was born.",
      "dismantle our military and enable Islamic terrorists to colonize America without resistance.",
      "hack into your Facebook account and send penile enlargement ads to all of your friends.",
      "do exactly what Hitler wrote about in the Communist Manifesto. They're all connected - liberals, Nazis, Kevin Bacon, everybody.",
      "silence you at gunpoint. These people are radicals, and they will not rest until you swear a loyalty oath to our Kenyan-born Fuhrer.",
      "blow up FOX News in a fiery apocalypse, just like the Mayan calendar predicts.",
      "kill you off and give your organs to an illegal immigrant.",
      "force all of us into Satanic atheist Muslim reeducation bathhouses.",
      "force you to gay-marry an illegal immigrant in a mosque at Ground Zero.",
      "operate secret abortion clinics that will only abort straight babies.",
      "erect a statue of Fidel Castro made out of recycled garden burger boxes right in front of the Pentagon.",
      "send you a computer virus which will set your home page to PlannedParenthood.org.",
      "blow up more offshore rigs and try to blame it on the oil companies, just like they did in the Gulf of Mexico. They are coming for us. We are all BP now.",
      "prevent law-abiding Americans from shooting abortion doctors. What ever happened to the ''land of the free''?"
    ]
  ]
  
  def generate(self):
    return ' '.join(map(lambda a: a[randint(0,len(a)-1)], self.parts))